import [
  "~/.config/alacritty/themes/themes/nordic.toml"
]

[font]
size = 6.0

[font.normal]
family = FiraCode Nerd Font

[font.bold]
family = FiraCode Nerd Font

[font.italic]
family = FiraCode Nerd Font

[window]
opacity = 0.97
